"use client";
import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ArrowDown, ArrowUpRight, Plus, Minus } from "lucide-react";
import "./portfolio.css";

const projects = [
 {name:"Chat-dot",tag:"AI / WEB APP",type:"chat",line:"One space. Many possibilities.",description:"An experiment in making AI feel a little more useful. Multiple models, a simple interface, and a place to turn thoughts into things.",href:"https://chat.adarsh-gupta.in",stack:"Next.js · Supabase",year:"2023"},
 {name:"Chat-with-News",tag:"AI / EXPLORATION",type:"news",line:"A conversation with context.",description:"What if catching up with the world felt like a conversation? A news companion that finds the context behind your questions.",href:"https://github.com/adarsh-gupta101/Chat-with-news",stack:"LangChain · Pinecone",year:"2023"},
 {name:"TransitX",tag:"MOBILE / REAL TIME",type:"map",line:"Less waiting. More knowing.",description:"A live bus-tracking app for college students. Built to answer one very practical question: where is my bus?",href:"https://github.com/adarsh-gupta101/TransitX",stack:"React Native · Node.js",year:"2022"},
 {name:"Draww-it",tag:"CREATIVE / MULTIPLAYER",type:"draw",line:"Same canvas. Different minds.",description:"A shared drawing space where ideas happen together. A playful exploration of real-time collaboration.",href:"https://github.com/adarsh-gupta101/NodeJS-SocketIO-Drawingtool",stack:"React · Socket.IO",year:"2022"},
];
function Sketch({type}:{type:string}) {
 const [mode,setMode]=useState(0);
 return <div className={`sketch sketch-${type}`}><div className="window-bar"><span>○ ○ ○</span><span>CONCEPT SKETCH / {type.toUpperCase()}</span><span>↗</span></div>
 {type==="chat"&&<div className="chat-ui"><span className="micro">A LITTLE ROOM FOR BIG IDEAS</span><h4>What are we<br/>making today?</h4><div className="mode-buttons">{["Think","Write","Build"].map((label,i)=><button key={label} onClick={()=>setMode(i)} aria-pressed={mode===i} className={mode===i?"active":""}>{label}</button>)}</div><div className="fake-input">{["Explain a complicated idea simply","Find the words for your next idea","Turn a thought into an interface"][mode]}<span>↑</span></div></div>}
 {type==="news"&&<div className="news-ui"><span className="micro">FOLLOW THE THREAD</span><div className="news-flow"><span>The world<br/><b>News & stories</b></span><i>→</i><span>The connection<br/><b>Find context</b></span><i>→</i><span>The conversation<br/><b>Better answers</b></span></div><h4>“What happened,<br/>and why does it matter?”</h4><div className="answer-lines"><i/><i/><i/></div></div>}
 {type==="map"&&<div className="map-ui"><svg viewBox="0 0 600 270" fill="none" aria-hidden="true"><path d="M0 80H600M0 190H600M100 0V270M270 0V270M470 0V270" stroke="#d1dbc9" strokeWidth="14"/><path d="M100 230V80H470V190H550" stroke="#2456ed" strokeWidth="4" strokeDasharray="8 5"/><circle cx="100" cy="230" r="8" fill="#2456ed"/><circle cx="550" cy="190" r="8" fill="#2456ed"/><circle cx="310" cy="80" r="20" fill="#2456ed"/><text x="310" y="86" textAnchor="middle" fill="white" fontSize="18">↗</text></svg><div className="map-note"><i className="dot"/> YOUR CAMPUS, CONNECTED<b>Next stop: less guesswork.</b></div></div>}
 {type==="draw"&&<div className="draw-ui"><svg viewBox="0 0 600 270" fill="none" aria-hidden="true"><path d="M150 185C60 38 310 15 255 145C215 233 360 245 395 95" stroke="#2456ed" strokeWidth="5" strokeLinecap="round"/><path d="M365 75L420 48L445 102M465 155C520 130 530 210 475 223" stroke="#dc825c" strokeWidth="5" strokeLinecap="round"/><circle cx="315" cy="76" r="24" stroke="#252622" strokeWidth="3"/></svg><span className="drawing-cursor">↖ <b>You</b></span><span className="drawing-cursor friend">↖ <b>A friend</b></span><p>A little messy. A lot more fun together.</p></div>}
 </div>;
}
export default function Page(){
 const root=useRef<HTMLDivElement>(null);
 const [expanded,setExpanded]=useState(false);
 useEffect(()=>{
  gsap.registerPlugin(ScrollTrigger);
  const mm=gsap.matchMedia();
  mm.add("(prefers-reduced-motion: no-preference)",()=>{
   gsap.from(".intro-reveal",{y:35,opacity:0,duration:1,stagger:.11,ease:"power3.out"});
   gsap.utils.toArray<HTMLElement>("[data-reveal]").forEach(el=>gsap.from(el,{y:32,opacity:0,duration:.8,scrollTrigger:{trigger:el,start:"top 92%",once:true}}));
   gsap.to(".outer-orbit",{rotation:-65,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:1}});
   gsap.to(".inner-orbit",{rotation:100,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:1}});
   gsap.to(".reading-progress",{scaleX:1,ease:"none",scrollTrigger:{start:0,end:"max",scrub:true}});
  },root);
  return ()=>mm.revert();
 },[]);
 return <div className="portfolio" ref={root}><div className="reading-progress" aria-hidden="true"/><a href="#main" className="skip-link">Skip to content</a>
 <header className="site-header"><a className="wordmark" href="#" aria-label="Adarsh Gupta home">adarsh<span>®</span></a><nav aria-label="Main navigation"><a href="#work">Work <small>01</small></a><a href="#about">About <small>02</small></a><a href="#contact">Let’s talk <ArrowUpRight size={15}/></a></nav></header>
 <main id="main"><section className="hero"><div className="hero-meta intro-reveal"><span><i className="dot"/> ENGINEER & CURIOUS HUMAN</span><span>BASED IN INDIA / BUILDING EVERYWHERE</span></div><div className="hero-grid"><div><h1 className="intro-reveal">Making<br/>complex things<br/><em>feel simple.</em></h1><div className="hero-description intro-reveal"><span>✳</span><p>I’m Adarsh Gupta. I build things for the web,<br className="desktop-break"/> follow my curiosity, and care about the details.</p></div><a className="explore intro-reveal" href="#work">Explore my work <span><ArrowDown size={19}/></span></a></div><div className="orbital-art intro-reveal" role="img" aria-label="Orbiting ideas around Adarsh’s initials"><span className="diagram-label">FIG. 01 — A MIND IN MOTION</span><div className="orbit outer-orbit"><i/><span>IDEAS</span></div><div className="orbit inner-orbit"><i/><span>SYSTEMS</span></div><div className="orbit-core"><b>ag.</b><small>ALWAYS ITERATING</small></div><span className="cross cross-one">+</span><span className="cross cross-two">+</span><div className="diagram-bottom"><span>INPUT: CURIOSITY</span><span>OUTPUT: SOMETHING USEFUL</span></div></div></div><div className="hero-bottom intro-reveal"><span>A LITTLE LOGIC. A LITTLE IMAGINATION.</span><span>SCROLL TO CONNECT THE DOTS <ArrowDown size={13}/></span></div></section>
 <section id="work" className="section-wrap"><div className="section-heading" data-reveal><span className="eyebrow">01 / SELECTED EXPLORATIONS</span><div><h2>Ideas, made real<span>.</span></h2><p>A few things I’ve built. Each started with a question.</p></div><span className="count">(04)</span></div><div className="projects">{projects.map((project,i)=><article className="project" key={project.name} data-reveal><Sketch type={project.type}/><div className="project-meta"><span>0{i+1} / {project.tag}</span><span>{project.year}</span></div><a href={project.href} target="_blank" rel="noopener noreferrer" className="project-title"><h3>{project.name}</h3><ArrowUpRight size={27}/></a><p className="project-line">{project.line}</p><p className="project-description">{project.description}</p><div className="project-foot"><span>{project.stack}</span><a href={project.href} target="_blank" rel="noopener noreferrer">{project.type==="chat"?"Visit project":"View source"} ↗</a></div></article>)}</div></section>
 <section id="about" className="section-wrap about-section"><div className="section-heading" data-reveal><span className="eyebrow">02 / A LITTLE ABOUT ME</span><h2>Built on curiosity<span>.</span></h2></div><div className="about-grid"><div className="about-story" data-reveal><h3>I like knowing how<br/>things <em>actually</em> work.</h3><p>Sometimes that means getting a backend to behave. Sometimes it means building an AI experiment or a canvas people can draw on together. I like both the logic and the little details that make something enjoyable to use.</p><p>Outside the code, I write about what I learn and keep looking for the next interesting question.</p><div className="socials"><a href="https://github.com/adarsh-gupta101" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/adarsh1gupta/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://www.youtube.com/@Paralaxxed" target="_blank" rel="noopener noreferrer">YouTube ↗</a></div></div><div className="about-note" data-reveal><div className="portrait"><Image src="/adarsh.jpg" alt="Adarsh Gupta" width="130" height="155" loading="lazy"/><span>ENGINEER. BUILDER.<br/>WORK IN PROGRESS.</span></div><button className="experience-button" aria-expanded={expanded} aria-controls="experience-detail" onClick={()=>setExpanded(!expanded)}><span><small>THE DAY JOB</small><strong>Systems Engineer at TCS</strong></span>{expanded?<Minus size={20}/>:<Plus size={20}/>}</button><p id="experience-detail" hidden={!expanded}>Working on enterprise backend systems, with a focus on reliable APIs and making the moving parts work better together.</p><div className="toolkit"><span className="eyebrow">THINGS I REACH FOR</span><p>Java · TypeScript · React · Next.js<br/>Node.js · Spring Boot · SQL · Docker</p></div></div></div></section>
 <section id="contact" className="section-wrap contact-section"><div data-reveal><span className="eyebrow">03 / THE NEXT CONNECTION</span><h2>Have something<br/>in <em>mind?</em><a href="mailto:adarshguptaworks@gmail.com" aria-label="Email Adarsh"><ArrowUpRight/></a></h2><div className="contact-row"><p>A project, an idea, or a good conversation.<br/>I’d love to hear about it.</p><a href="mailto:adarshguptaworks@gmail.com">adarshguptaworks@gmail.com ↗</a></div></div></section></main>
 <footer className="site-footer"><span>© {new Date().getFullYear()} ADARSH GUPTA</span><span>THOUGHTFULLY BUILT. ALWAYS EVOLVING.</span><a href="#">Back to top ↑</a></footer></div>;
}
